### ISSUE TITLE
Older era temperate climate buildings appear in sub-tropic climate (possibly intentional?)

### ISSUE THREAD

**Issue by Seriphyn17** [2TallTyler/itl_houses#41]
![image](https://user-images.githubusercontent.com/131037821/232684625-0815d3d6-77cc-4abd-8c4a-762ed0d53364.png)

As seen in the middle of this city, a handful of buildings that originate in the temperate climate have appeared here. I was unsure if this was intentional, but upon checking the scenario editor, these buildings Years are 1700 to 65535, and are the only buildings to have that date range. That would appear like an oversight to me in which case?

![image](https://user-images.githubusercontent.com/131037821/232685458-5eefaa62-2136-4ee2-990c-9a73adb0010e.png)

**Comment by 2TallTyler** [comment]
This one is intentional, yes. 😃
